spring.profiles.active: develop
server:
  port: 8090
  servlet:
    context-path: /is-wallet-service
spring:
  application:
    name: wallet-service
management:
  endpoints:
    web:
      exposure:
        include: '*'
---
spring:
  h2:
    console:
      enabled: true
      path: /h2
    datasource:
      username: sa
      password:
      driverClassName: org.h2.Driver
  config:
    activate:
      on-profile: develop
stripe.simulator.charges-uri: 'https://sandbox.playtomic.io/v1/stripe-simulator/charges'
stripe.simulator.refunds-uri: 'https://sandbox.playtomic.io/v1/stripe-simulator/payments/{payment_id}/refunds'
---
spring:
  h2:
    console:
      enabled: true
      path: /h2
    datasource:
      url: jdbc:h2:mem:testdb
      username: sa
      password:
      driverClassName: org.h2.Driver
  config:
    activate:
      on-profile: test
stripe.simulator.charges-uri: http://localhost:9999
stripe.simulator.refunds-uri: http://localhost:9999